"""Figure 2 - the secondary analysis.

Both pre-specified attainment curves across K = 7-49, with K = 21 marked. This
is subordinate to Figure 1: the audit is the result, and this curve is reported
only because it was pre-specified and because its headline criterion was not met.

Every number drawn or quoted is a key in numbers.json, asserted before the file
is written. Palette: dataviz reference instance, categorical slots 1 and 2.
"""
from __future__ import annotations
import argparse, json, sys, textwrap
from pathlib import Path
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

HERE = Path(__file__).resolve().parent
H, K_PRIMARY, N_COHORT = 49, 21, 60

THEME = {
    "light": dict(surface="#fcfcfb", ink="#0b0b0b", ink2="#52514e", muted="#8a8983",
                  grid="#e4e3df", rule="#c9c7c0", loose="#2a78d6", primary="#eb6834"),
    "dark":  dict(surface="#1a1a19", ink="#ffffff", ink2="#c3c2b7", muted="#8a8983",
                  grid="#2e2e2c", rule="#4a4a45", loose="#3987e5", primary="#d95926"),
}


def build_caption(n):
    """The caption text actually handed to the renderer.

    Separated from draw() so the suite can assert on the GENERATED strings
    and their numbers. Searching the source file would also match a comment
    or an unused literal, which is not the same guarantee.
    """
    b = n["bootstrap"]
    c = n["usable_day_curve_K7_to_K49"]
    return [
        ("Design.",
         f"N = {n['fixed_horizon_cohort_n_participants']} fixed-horizon participants, each observed "
         f"over the retained H = {n['observation_horizon_H_days']}-day window. A participant reaches K "
         f"on accumulating K usable days inside that window. primary is a subset of loose (equality permitted, and observed at low K), so "
         f"its curve can never sit above."),
        ("At K = 21.",
         f"{c['21']['loose_n']} of {N_COHORT} ({c['21']['loose']}%) under loose against "
         f"{c['21']['primary_n']} of {N_COHORT} ({c['21']['primary']}%) under primary; observed ratio "
         f"{n['observed_yield_ratio_primary_over_loose']}. Planning estimates to finish with 50 "
         f"completers: {n['enroll_for_50_at_K21_loose']} against "
         f"{n['enroll_for_50_at_K21_primary']} enrolled."),
        ("Criterion not met.",
         f"The pre-specified test asks whether the bootstrap 95% CI for the ratio excludes 1.0. It does "
         f"not: {b['yield_ratio_ci_lo_unrounded']:.4f} to {b['yield_ratio_ci_hi_unrounded']:.4f}. Null "
         f"condition 2 fired and the signal-choice result is reported as an inconclusive secondary "
         f"analysis. This is not a finding of no difference."),
        ("Horizon.",
         f"H = {n['observation_horizon_H_days']} was the committed horizon; corrected execution of the "
         f"selection rule yields {n['H_rule_reexecuted_under_corrected_calendar']}. The committed "
         f"analysis was retained, which preserves the named horizon but departs from the correctly "
         f"executed rule (WINDOW_RULE.md 8.2). No significance is claimed at any K."),
        ("",
         "LifeSnaps (Yfantidou et al., Sci Data 2022; Zenodo 7229547, CC-BY 4.0). Every figure quoted "
         "is a key in numbers.json; regenerated by figure2.py."),
    ]


def draw(mode, n, out_dir=None):
    t = THEME[mode]
    c = n["usable_day_curve_K7_to_K49"]
    Ks = list(range(7, H + 1))
    loose = [c[str(k)]["loose"] for k in Ks]
    prim = [c[str(k)]["primary"] for k in Ks]

    fig, ax = plt.subplots(figsize=(11.4, 10.4))
    fig.patch.set_facecolor(t["surface"]); ax.set_facecolor(t["surface"])

    ax.set_axisbelow(True)
    ax.grid(axis="y", color=t["grid"], lw=1, zorder=0)
    ax.axvline(K_PRIMARY, color=t["rule"], lw=1.1, ls=(0, (3, 3)), zorder=1)

    ax.plot(Ks, loose, color=t["loose"], lw=2, zorder=3, solid_capstyle="round")
    ax.plot(Ks, prim, color=t["primary"], lw=2, zorder=3, solid_capstyle="round")

    kL = c[str(K_PRIMARY)]["loose"]; kP = c[str(K_PRIMARY)]["primary"]
    for y, col in ((kL, t["loose"]), (kP, t["primary"])):
        ax.plot([K_PRIMARY], [y], "o", ms=9, color=col, zorder=5,
                mec=t["surface"], mew=2)

    # direct labels at the right end, so identity is never colour-alone
    ax.text(H + 0.6, loose[-1], "  loose", color=t["loose"], fontsize=10,
            va="center", ha="left", weight="bold")
    ax.text(H + 0.6, prim[-1], "  primary", color=t["primary"], fontsize=10,
            va="center", ha="left", weight="bold")

    ax.annotate(f"K = {K_PRIMARY}, the pre-specified primary target\n"
                f"{c[str(K_PRIMARY)]['loose_n']} of {N_COHORT} ({kL}%) loose  ·  "
                f"{c[str(K_PRIMARY)]['primary_n']} of {N_COHORT} ({kP}%) primary",
                xy=(K_PRIMARY, kP), xytext=(K_PRIMARY + 3.4, 41),
                color=t["ink"], fontsize=9.5, ha="left", va="center", zorder=6,
                arrowprops=dict(arrowstyle="-", color=t["muted"], lw=1,
                                connectionstyle="angle,angleA=0,angleB=90,rad=4"))

    # Full 0-100% scale: it gives attainment percentages their natural context.
    # It does NOT establish that any gap between the curves is or is not
    # practically important - this analysis does not settle that question.
    ax.set_xlim(7, H + 5.4); ax.set_ylim(0, 100)
    ax.set_xticks([7, 14, 21, 28, 35, 42, 49])
    ax.set_yticks(range(0, 101, 20))
    ax.set_yticklabels([f"{v}%" for v in range(0, 101, 20)])
    ax.set_xlabel("K — usable days required within the 49-day window",
                  color=t["ink2"], fontsize=10, labelpad=9)
    ax.set_ylabel(f"share of the {N_COHORT} fixed-horizon participants reaching K",
                  color=t["ink2"], fontsize=10, labelpad=9)
    ax.tick_params(colors=t["ink2"], labelsize=9, length=0)
    for s in ("top", "right", "left"):
        ax.spines[s].set_visible(False)
    ax.spines["bottom"].set_color(t["grid"])

    ax.legend(handles=[plt.Line2D([], [], color=t["loose"], lw=2, label="loose — steps recorded"),
                       plt.Line2D([], [], color=t["primary"], lw=2,
                                  label="primary — steps and resting heart rate")],
              loc="lower left", frameon=False, fontsize=9.5, labelcolor=t["ink2"],
              bbox_to_anchor=(0.0, 0.02))

    fig.text(0.072, 0.972, "Secondary analysis: usable-day attainment under two definitions",
             color=t["ink"], fontsize=14.5, weight="bold", ha="left", va="top")
    fig.text(0.072, 0.940,
             "The pre-specified headline criterion was not met. Figure 1 is the main result.",
             color=t["ink2"], fontsize=10.5, ha="left", va="top")

    cap = build_caption(n)
    LX, TX, WRAP = 0.072, 0.215, 115
    y = 0.325
    for label, body in cap:
        ink = t["ink2"] if label else t["muted"]
        if label:
            fig.text(LX, y, label, color=t["ink"], fontsize=9, weight="bold", ha="left", va="top")
        for line in textwrap.wrap(body, WRAP):
            fig.text(TX if label else LX, y, line, color=ink, fontsize=9, ha="left", va="top")
            y -= 0.0175
        y -= 0.007

    fig.subplots_adjust(left=0.105, right=0.885, top=0.905, bottom=0.405)
    out = Path(out_dir or HERE) / f"figure2_{mode}.png"
    fig.savefig(out, dpi=200, facecolor=t["surface"])
    plt.close(fig)
    return out


def main():
    n = json.loads((HERE / "numbers.json").read_text())
    c = n["usable_day_curve_K7_to_K49"]

    # caption assertions - nothing is written unless these hold
    assert n["fixed_horizon_cohort_n_participants"] == N_COHORT
    assert n["observation_horizon_H_days"] == H
    assert c[str(K_PRIMARY)]["loose_n"] == n[f"reaching_K{K_PRIMARY}_loose_n_of_{N_COHORT}"]
    assert c[str(K_PRIMARY)]["primary_n"] == n[f"reaching_K{K_PRIMARY}_primary_n_of_{N_COHORT}"]
    assert n["headline_criterion_met"] is False and n["null_condition_2_fired"] is True
    for k in range(7, H + 1):                       # nesting must hold everywhere drawn
        assert c[str(k)]["primary_n"] <= c[str(k)]["loose_n"]
    print(f"  curve K=7..{H}; at K={K_PRIMARY}: "
          f"{c['21']['loose_n']}/{N_COHORT} loose, {c['21']['primary_n']}/{N_COHORT} primary")
    ap = argparse.ArgumentParser()
    ap.add_argument('--out-dir', default=None,
                    help='write the PNGs here instead of beside this script')
    out_dir = ap.parse_args().out_dir
    for mode in ("light", "dark"):
        print("  wrote", draw(mode, n, out_dir))


if __name__ == "__main__":
    main()
